2022-02-24 15:14:18,546 INFO    MainThread:28659 [wandb_setup.py:_flush():69] setting env: {'project': 'telco_churn', 'run_group': 'development'}
2022-02-24 15:14:18,547 WARNING MainThread:28659 [wandb_setup.py:_flush():69] could not save program above cwd: /Users/jelaleddin/anaconda3/envs/mlflow-d1fd4b13aac386abe6aa5a2ada1ca11214902ce4/bin/pytest
2022-02-24 15:14:18,547 INFO    MainThread:28659 [wandb_setup.py:_flush():69] setting login settings: {}
2022-02-24 15:14:18,547 INFO    MainThread:28659 [wandb_init.py:_log_setup():334] Logging user logs to /Users/jelaleddin/MLPipeline-TelcoCustomerChurn/components/check_data/wandb/run-20220224_151418-376tdk7x/logs/debug.log
2022-02-24 15:14:18,547 INFO    MainThread:28659 [wandb_init.py:_log_setup():335] Logging internal logs to /Users/jelaleddin/MLPipeline-TelcoCustomerChurn/components/check_data/wandb/run-20220224_151418-376tdk7x/logs/debug-internal.log
2022-02-24 15:14:18,548 INFO    MainThread:28659 [wandb_init.py:init():367] calling init triggers
2022-02-24 15:14:18,548 INFO    MainThread:28659 [wandb_init.py:init():372] wandb.init called with sweep_config: {}
config: {}
2022-02-24 15:14:18,549 INFO    MainThread:28659 [wandb_init.py:init():416] starting backend
2022-02-24 15:14:18,549 INFO    MainThread:28659 [backend.py:_multiprocessing_setup():69] multiprocessing start_methods=spawn,fork,forkserver, using: spawn
2022-02-24 15:14:18,570 INFO    MainThread:28659 [backend.py:ensure_launched():123] starting backend process...
2022-02-24 15:14:18,581 INFO    MainThread:28659 [backend.py:ensure_launched():127] started backend process with pid: 28667
2022-02-24 15:14:18,586 INFO    MainThread:28659 [wandb_init.py:init():421] backend started and connected
2022-02-24 15:14:18,592 INFO    MainThread:28659 [wandb_init.py:init():461] updated telemetry
2022-02-24 15:14:18,595 INFO    MainThread:28659 [wandb_init.py:init():480] communicating current version
2022-02-24 15:14:23,596 INFO    MainThread:28659 [wandb_init.py:init():493] communicating run to backend with 30 second timeout
2022-02-24 15:14:53,599 INFO    MainThread:28659 [interface.py:_communicate_run():635] couldn't get run from backend
2022-02-24 15:14:53,599 ERROR   MainThread:28659 [wandb_init.py:init():497] backend process timed out
2022-02-24 15:14:53,599 ERROR   MainThread:28659 [wandb_init.py:init():506] encountered error: Error communicating with wandb process
try: wandb.init(settings=wandb.Settings(start_method='fork'))
or:  wandb.init(settings=wandb.Settings(start_method='thread'))
For more info see: https://docs.wandb.ai/library/init#init-start-error
2022-02-24 15:16:13,763 INFO    MainThread:28659 [wandb_init.py:teardown():185] tearing down wandb.init
